# [Info]
site_name: DongGuan # å·¦ä¸Šè§’æ ‡é¢˜
site_url: https://WebMing19.github.io
site_author: Ethan Han
site_description: ä¸œè§‚

# [UI]
## [top]
theme:
  name: material
  palette:
    - scheme: default # æ—¥é—´æ¨¡å¼
      primary: indigo # ä¸Šæ–¹çš„
      accent: orange # é“¾æ¥ç­‰å¯äº¤äº’å…ƒä»¶çš„é«˜äº®è‰²
      toggle:
        icon: material/weather-night # å›¾æ ‡
        name: åˆ‡æ¢è‡³å¤œé—´æ¨¡å¼ # é¼ æ ‡æ‚¬æµ®æç¤º
    - scheme: slate # å¤œé—´æ¨¡å¼
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: åˆ‡æ¢è‡³æ—¥é—´æ¨¡å¼
  features:
    - navigation.tabs # ä½¿ç”¨Tabæ¥è¿›è¡Œåˆ†ç±»
    - navigation.top # è¿”å›é¡¶éƒ¨çš„æŒ‰é’® åœ¨ä¸Šæ»‘æ—¶å‡ºç°
    - navigation.indexes # Tabä¼šæœ‰ä¸€ä¸ªindex.md è€Œä¸æ˜¯åœ¨æ‰“å¼€Tabæ—¶æ‰“å¼€ç¬¬ä¸€ç¯‡æ–‡ç« 
    - navigation.expand # æ‰“å¼€Tabæ—¶å·¦ä¾§ç›®å½•å…¨éƒ¨å±•å¼€
    - search.suggest # æœç´¢è¾“å…¥ä¸€äº›å­—æ¯æ—¶æ¨èè¡¥å…¨æ•´ä¸ªå•è¯
    - search.highlight # æœç´¢å‡ºçš„æ–‡ç« å…³é”®è¯åŠ å…¥é«˜äº®
  language: zh # ä¸€äº›æç¤ºæ€§çš„æ–‡å­—ä¼šå˜æˆä¸­æ–‡
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # ç¼–è¾‘æŒ‰é’®è·³è½¬çš„é“¾æ¥
## [top-right corner]
repo_url: https://github.com/Webming19 # å³ä¸Šè§’ç‚¹å‡»è·³è½¬çš„é“¾æ¥
repo_name: GitHub | Ethan Han # å³ä¸Šè§’çš„åå­—
## [bottom-left corner]
copyright: Copyright &copy; 2023 Ethan Han # å·¦ä¸‹è§’çš„ç‰ˆæƒå£°æ˜
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/github # å›¾æ ‡
      link: https://github.com/Webming19 # è·³è½¬é“¾æ¥
      name: GitHub | Ethan Han # é¼ æ ‡æ‚¬æµ®æç¤º
    - icon: fontawesome/brands/bilibili
      link: https://bilibili.com
      name: Bilibili

# [Navigation]
nav:
  - åšå®¢ğŸ“‘:
      - BLOG/index.md
      - ç½‘ç«™:
          - MkDocsé™æ€ç½‘ç«™æ„å»º: BLOG/Markdown/mkdocs-site.md
      - å‰ç«¯:
          - JSéšå¼ç±»å‹è½¬æ¢: BLOG/FrontEnd/JSéšå¼ç±»å‹è½¬æ¢.md
  - é¡¹ç›®ğŸ—:
      - PROJECT/index.md
      - å‰ç«¯æ¶æ„:
          - Vue: PROJECT/FrontEnd/vue.md
      - åç«¯æ¶æ„:
          - Nest: PROJECT/BackEnd/nest.md

  - çŸ¥è¯†ğŸ§€:
      - Learn/index.md
      - åŸºç¡€çŸ¥è¯†:
          - ç½‘ç»œ:
              - çŸ¥è¯†ç‚¹æ€»ç»“: Learn/Network/learning.md
              - ä¸“æœ‰åè¯é€ŸæŸ¥: Learn/Network/nouns.md
              - GraphQL Hasura: Learn/Network/graphql.md
      - Linux:
          - vim: Learn/Linux/vim.md
          - tmux: Learn/Linux/tmux.md
          - UNIX: Learn/Linux/unix.md
      - macOS:
          - ä½¿ç”¨treeå‘½ä»¤å’Œè®¿è¾¾è¿›è¡Œä»»åŠ¡ç®¡ç†: Learn/macOS/tree.md
          - è¾…åŠ©åŠŸèƒ½ç¼©æ”¾: Learn/macOS/zoom.md
          - Macä¸Androidçš„æ–‡ä»¶ä¼ è¾“: Learn/macOS/sharing-mac-android.md
          - MADåˆ¶ä½œæµç¨‹: Learn/macOS/mad.md
          - OBSå¼€ç›´æ’­: Learn/macOS/stream.md
      - Markdown:
          - Markdownè¯­æ³•åˆå­¦ä¹ : Learn/Markdown/grammars.md
          - TODO ExMarkè§„èŒƒ: Learn/Markdown/ExMark-spec-zh.txt
          - MkDocsé™æ€ç½‘ç«™æ„å»º: Learn/Markdown/mkdocs-site.md
          - mdBooké™æ€ç½‘ç«™æ„å»º: Learn/Markdown/mdbook-site.md
          - GitHub Pagesç®€ä»‹: Learn/Markdown/github-pages.md

# [Extensions]
plugins:
  - search: # ç°åœ¨è¿˜ä¸æ”¯æŒä¸­æ–‡æœç´¢ æ”¯æŒä¹‹åå¯ä»¥è®¾ç½®è¯­è¨€
      # insiderå·²ç»æ”¯æŒä¸­æ–‡çš„åˆ†è¯æœç´¢äº† https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
  - tags # ç»™å•ç¯‡æ–‡ç« æ·»åŠ æ ‡ç­¾ https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
# []
markdown_extensions:
  - pymdownx.arithmatex: # latexæ”¯æŒ
      generic: true
  - attr_list # ç»™å›¾ç‰‡åé¢æ·»åŠ {width="300"}è®¾ç½®å¤§å°
  - toc:
      permalink: true # å›ºå®šæ ‡é¢˜ä½ç½®ä¸ºå½“å‰ä½ç½®
  - pymdownx.highlight: # ä»£ç å—é«˜äº®
    # linenums: true # æ˜¾ç¤ºè¡Œå·
    # auto_title: true # æ˜¾ç¤ºç¼–ç¨‹è¯­è¨€åç§°
  - pymdownx.superfences # ä»£ç å—é«˜äº®æ’ä»¶
  - meta # æ”¯æŒMarkdownæ–‡ä»¶ä¸Šæ–¹è‡ªå®šä¹‰æ ‡é¢˜æ ‡ç­¾ç­‰
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonitionéœ€è¦

# [JavaScriptæ”¯æŒ]
extra_javascript:
  # latexæ”¯æŒ
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0

# [cssæ”¯æŒ]
extra_css:
  - mkdocs/css/no-footer.css # ä¸ä½¿ç”¨åº•éƒ¨çš„ç¿»é¡µ
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols
